"""add user nudge preferences

Revision ID: 07d3ea7f887d
Revises: 37b38571f0a5
Create Date: 2026-07-24 16:48:55.229425

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07d3ea7f887d"
down_revision: Union[str, None] = "37b38571f0a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "notification_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "overlay_enabled", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "audio_enabled", sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "audio_enabled")
    op.drop_column("users", "overlay_enabled")
    op.drop_column("users", "notification_enabled")
    # ### end Alembic commands ###
